### ISSUE TITLE
Error on empty data

### ISSUE THREAD

**Issue by Finesse** [alexcaza/export-to-csv#10]
### How to reproduce

Run

```js
import { ExportToCsv } from 'export-to-csv';

const csvExporter = new ExportToCsv({
  showLabels: true,
  headers: ['First', 'Second'],
});
const data = [];
csvExporter.generateCsv(data);
```

### Expected result

The following CSV file is produced:

```csv
First,Second

```

### Actual result

An exception is throw: «Cannot convert undefined or null to object».

<img width="478" alt="image" src="https://user-images.githubusercontent.com/9006227/63946821-23ce6480-cab9-11e9-81e4-d9810bbdac32.png">

**Comment by Finesse** [comment]
I use a workaround for this bug:

```diff
import { ExportToCsv } from 'export-to-csv';

const csvExporter = new ExportToCsv({
-   showLabels: true,
-   headers: ['First', 'Second'],
});
const data = [];
- csvExporter.generateCsv(data);
+ csvExporter.generateCsv([
+   ['First', 'Second'],
+   ...data,
+ ]);
```

**Comment by BlackTafita** [comment]
I got the same problem, and the solution from above looks messy, to say the least.
Is there any progress towards solving this problem?

**Comment by Finesse** [comment]
I'm not the author of this library, so I can't fix the problem. Your 👎s are addressed to a person with the same problem and the same possibilities. I did all I could to help me and you. If the workaround doesn't work or you don't like it for some other reason, please leave a comment to improve the workaround.

**Comment by BlackTafita** [comment]
I'm sorry if I offended you and I addressed my previous comment to developers of this library to make this flow normally. I can create a pull request to fix this issue but as I understand no one from devs doesn't care about this. Because no one was assigned to this task.
Your fix is working and I can't find another solution but it's not the normal way that`s all that I mean.

**Comment by Finesse** [comment]
Yes, that's why I call it "a workaround" (костыль)

**Comment by alexcaza** [comment]
This has been addressed in `v1.x.x`. There will also be a `CsvGenerationError` thrown if `columnHeaders` is empty _and_ there is no data passed.
