### ISSUE TITLE
Type error: Module '"export-to-csv"' has no exported member 'generateCsv'.

### ISSUE THREAD

**Issue by Mtbd83** [alexcaza/export-to-csv#100]
at compilation : Type error: Module '"export-to-csv"' has no exported member 'generateCsv'.

I have installed the package and I can use it. But not working at compilation

**Comment by alexcaza** [comment]
Great! This is probably related to https://github.com/alexcaza/export-to-csv/issues/88#issuecomment-1984886892 😄 

Closing the issue.
