### ISSUE TITLE
Handling of inconsistent object definitions

### ISSUE THREAD

**Issue by sfw185** [alexcaza/export-to-csv#11]
I've encountered an issue where we're creating CSV from a list of objects. The objects vary in that they share a base set of keys, but also have ad-hoc keys that exist in some objects, but not all of them.

The actual output includes a lot of "undefined" and "null" which is not very useful for a CSV file. The expected behaviour is to treat any null or undefined as a blank string instead for the purpose of transforming to CSV.

Example Input:
```json
[
  { "key1": "Value 1", "key2": "Value 2", "key3": "Value 3"},
  { "key1": "Value 1", "key2": "Value 2", "key4": "Value 4"},
]
```

Example Output:

```csv
key1,key2,key3,key4
Value 1, Value 2, Value 3, undefined
Value 1, Value 2, undefined, value 4
```

Expected Output:

```csv
key1,key2,key3,key4
Value 1, Value 2, Value 3,
Value 1, Value 2,, value 4
```

**Comment by leodelgadodev** [comment]
bump

**Comment by michaelgu95** [comment]
Not ideal, but you can go through any of the rows with missing collumn value and assign an empty string:

`                  data = data.map(obj => {
                    // Set empty string for any missing columns (otherwise it displays as undefined)
                    const missingColumns = _.difference(
                      columnHeaders,
                      _.keys(obj)
                    );
                    if (!_.isEmpty(missingColumns)) {
                      missingColumns.forEach(missingColumn => {
                        obj[missingColumn] = '';
                      });
                    }
                    return obj;
                  })`

**Comment by alexcaza** [comment]
I think that what @michaelgu95 is suggesting makes the most sense. Ideally, the consumer of the library should take care of most—if not all—of the data transformations / normalization before being passed to the generate function.

However, I can see there being some benefit to offering an option to change how `undefined` values are handled. Which was suggested in #26 ages ago.

Here's what I'm thinking to deal with collections containing objects of various shapes:
- Port the code in PR #26 to work in the context of v1.0.0, then you could
- Transform the data to normalize the objects in the collection + use a default value for `undefined` through the config
- Or, use the `columnHeaders` option and list out all of the possible keys, in the order you want + use a default value for `undefined` through the config

I'd rather not have the library deal with dynamically finding all the keys within the collection. Given a large collection, the library would have no choice but to iterate over the entire collection to build the header list, and then iterate over it again to build the CSV data. This would impact performance quite a bit for large collections when instead the transformations could be done once by the caller.
