### ISSUE TITLE
export-to-csv dependency not found

### ISSUE THREAD

**Issue by modermo** [alexcaza/export-to-csv#115]
**Bug**
Upgrading from 0.2.1 to 1.4.0 causes an issue in a Vue app where `export-to-csv- is not found as a dependency

**Reproduce**
`import { generateCsv, mkConfig } from "export-to-csv"` results in the below:

```
ERROR  Failed to compile with 1 errors

This dependency was not found:

* export-to-csv in ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/components/hello-world.vue?vue&type=script&lang=js&
*
```

**Expected behaviour**
After running `npm install --save export-to-csv` the dependency should be found, especially given it's appearing in my package.json

See my package.json file below:

```
{
  "name": "vue-project",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "serve": "vue-cli-service serve",
    "build": "vue-cli-service build",
    "lint": "vue-cli-service lint",
    "deploy": "git push platform master",
    "buildenvvar": "platform-var dist",
    "dev": "vue-cli-service serve"
  },
  "dependencies": {
    "axios": "^0.20.0",
    "core-js": "^3.6.5",
    "export-to-csv": "^1.4.0",
    "vue": "^2.6.11"
  },
  "devDependencies": {
    "@vue/cli-plugin-babel": "~4.5.0",
    "@vue/cli-plugin-eslint": "~4.5.0",
    "@vue/cli-service": "~4.5.0",
    "babel-eslint": "^10.1.0",
    "eslint": "^6.7.2",
    "eslint-plugin-vue": "^7.0.0-beta.3",
    "vue-template-compiler": "^2.6.11"
  },
  "eslintConfig": {
    "root": true,
    "env": {
      "node": true
    },
    "extends": [
      "plugin:vue/essential",
      "eslint:recommended"
    ],
    "parserOptions": {
      "parser": "babel-eslint"
    },
    "rules": {}
  },
  "browserslist": [
    "> 1%",
    "last 2 versions",
    "not dead"
  ]
}
```

**Comment by alexcaza** [comment]
I'm not familiar with Vue's "default" build system, so I might be missing something. I do suspect it's related to this library no longer being a commonjs module ([see this issue](https://github.com/alexcaza/export-to-csv/issues/88)).

If you can't switch to using ESM within your project, then I'm afraid the latest version won't work for your needs (feel free to check out [a list of alternatives in the README](https://github.com/alexcaza/export-to-csv/issues/88) if you'd like a replacement).

Also, feel free to drop a stackblitz—or similar online REPL—with a reduced test-case I can play around with if you'd like more help 😄

**Comment by modermo** [comment]
Ah, got it. I'll see if there is an issue on the Vue end, otherwise you can close this! Thank you!
