### ISSUE TITLE
Open OS save modal

### ISSUE THREAD

**Issue by JustinSchieck** [alexcaza/export-to-csv#15]
Hello,

Not so much an issue as a possible feature question, Is there a way or can a way be implemented to allow the developer to leave the file name blank, and allow the user to set it through a save window?  similar to the way word saves a document or excel. 

If so, let me know as I've implemented this library and may switch out if not a possibility. works well otherwise btw.

**Comment by JustinSchieck** [comment]
decided to use windows.prompt but wonder if there is a better way that can use the actual save modal

**Comment by alexcaza** [comment]
The most reliable way would likely be the File System API's `showSaveFilePicker` method ([MDN docs](https://developer.mozilla.org/en-US/docs/Web/API/window/showSaveFilePicker)). Sadly support isn't great right now, and it's still an experimental API.

For the time being, I'd leave it up to the caller of this library to determine the best way to ask the user for a file name. If the File System API stabilizes, and I notice that it has, I'll consider adding it!
