### ISSUE TITLE
Error 404 on all browser except chrome

### ISSUE THREAD

**Issue by alepau87** [alexcaza/export-to-csv#16]
after launch csvExporter.generateCsv(data);

goes to https://siteurl/blob:/2d9a393d-889f-4542-86bd-dbdd4cbd67d2 and gives 404 error

**Comment by jimmywim** [comment]
I'm also getting this in Chrome 80

**Comment by amatisea** [comment]
This is happening on chrome for SPO. I have found this https://github.com/SharePoint/sp-dev-docs/issues/4958 

Looks like In order to have blobs resume downloading like they used to, the new `data-interception="off" ` property is required.

`link.dataset.interception = 'off'`
