### ISSUE TITLE
How can Download data with nexted array?

### ISSUE THREAD

**Issue by vishnusinghchauhan** [alexcaza/export-to-csv#19]
Hello All,

Can anyone help me to download CSV with Nexted Array?

{

"name" : "rohit",
"email" : "rohit@gmail.com",
"phone" : "123",
"activity_array" : [ 
    {
        "activity_desc" : "First time Registration",
        "activity_title" : "User Registration",
    }, 
    {
        "activity_desc" : "fadsf\nadsf\nadsf\nsa\nf\nsf\nsdf",
        "activity_title" : "reagarding salary",
    }, 
    {
        "activity_desc" : "adfa",
        "activity_title" : "fanl",
    }
]
}

**Comment by cyrilselasi** [comment]
I don't know if there's a better way to do this but here's how i handled it:

1. Sort the data by the longest "activity_array" first. This package uses the first items `data[0]` keys as the CSV header so if you don't sort by longest first, some data will not be shown.

2. Iterate over the data and for reach activity_array item, dynamically add a new field (you can use the index as the unique value). Example: `data["activity_desc_" + index] = item.activity_desc` where item is the iterator value, data is your JSON data and index is the current iteration.

3. You'll end up with CSV header like `name, email, activity_desc_0, activity_title_0, activity_desc_1, ...` etc.

Hope this helps.

**Comment by alexcaza** [comment]
I think @cyrilselasi suggestions work well. This library is really only designed to handle flat data structures. Anything more complex and it becomes almost impossible to determine what output would be correct. It's up to the implementor to do the data transformations.

If anyone has strong opinions on why/how this library could/should solve this problem, please open an issue with some suggestions for what the APIs could look like.
