### ISSUE TITLE
Blob is not defined

### ISSUE THREAD

**Issue by ninthz** [alexcaza/export-to-csv#2]
Hey guys I got this error 

`ReferenceError: Blob is not defined`

What I must to update something?

Thanks

**Comment by Maado** [comment]
use it this way ,
`  const exportToCsv = new ExportToCsv(options);
  const x = exportToCsv.generateCsv(data, true);`

**Comment by mbonig** [comment]
But why!?

**Comment by femanso** [comment]
I had this issue and @Maado 's solution works, but just complementing the information answering @mbonig :
The module creates a Blob, which is only available on browsers, when you run it server-side (node), Blob is not defined. If you set true as the second arg, the function returns before the Blob call:

```
if (shouldReturnCsv) {
  return this._csv;
}

let blob = new Blob([this._csv], { "type": "text/csv;charset=utf8;" });
```

Blobs are used for downloading files from the browser, if you need to save the csv file, here is how I did it: 

```
const fs = require('fs')
const csvData = csvExporter.generateCsv(documents, true)
fs.writeFileSync('data.csv',csvData)
```

**Comment by srodriguezg** [comment]
@femanso Thank you very much to the answer, was very useful.

**Comment by goldylucks** [comment]
@femanso 's answer should go into the documentation. It's very unclear what to do after calling `generateCsv`

**Comment by mirao** [comment]
I got 
```
navigator is not defined
      at ExportToCsv.generateCsv (/home/mirao/workspace/codeceptjs/node_modules/.pnpm/export-to-csv@0.2.1/node_modules/export-to-csv/build/export-to-csv.js:86:9)
```
when running the sample from https://www.npmjs.com/package/export-to-csv in NodeJS 18

The solution https://github.com/alexcaza/export-to-csv/issues/2#issuecomment-419338681 works.
Thanks!
