### ISSUE TITLE
Not exporting more than 40 columns 

### ISSUE THREAD

**Issue by ezhil30sep** [alexcaza/export-to-csv#22]
Hi, 
I tried this library for my project and it is not exporting more than 40 columns where I have 47 colimns in my table(json). Also it shows the empty field as undefined..

**Comment by alexcaza** [comment]
I can't reproduce the issue with 40 columns being the limit. If this is still a relevant issue for you, please open another issue and, if you could, add the collection you're trying to convert to CSV (with any sensitive data removed).
