### ISSUE TITLE
Warning: unstable_flushDiscreteUpdates: Cannot flush updates when React is already rendering

### ISSUE THREAD

**Issue by fazzaMmsApis** [alexcaza/export-to-csv#25]
I am getting this warning issue 
Warning: unstable_flushDiscreteUpdates: Cannot flush updates when React is already rendering.
    in ExportToCSV

**Comment by kyle-villeneuve** [comment]
most likely your setState function has a side effect that is triggering another setState call, doesnt seem like an issue related to this library.
