### ISSUE TITLE
Cannot handle value of 0 - creates empty cell instead of cell with '0'

### ISSUE THREAD

**Issue by HeyParkerJ** [alexcaza/export-to-csv#27]
I would image there's some faulty falsey evaluation going on in the library

**Comment by HeyParkerJ** [comment]
the idiot is me

**Comment by OmarSherif96** [comment]
@HeyParkerJ how did you resolve the 0 value cells ? I am facing the same issue returning empty cells instead of 0

**Comment by HeyParkerJ** [comment]
@OmarSherif96 I believe I was doing some poor truthy/falsy checking logic to the tune of:

```
if (rowData) { // attempting to check for null/undefined but will fail if a cell value is 0
  populateCSVWithRowData(rowData);
}
```


My apologies for closing without explaining - I was very embarrassed at the time 😅
