### ISSUE TITLE
Capture CSV file before downloading

### ISSUE THREAD

**Issue by akhi9** [alexcaza/export-to-csv#30]
Hi, @alexcaza , Is there a way to capture the generated CSV file (so that one can send that file to the server-side) rather than downloading it on client-side

**Comment by xaphod** [comment]
Seems to be answered in https://github.com/alexcaza/export-to-csv/issues/2 -- just pass true as second arg, like this: 
`const csvData = csvExporter.generateCsv(doc, true)`
