### ISSUE TITLE
Export CSV with string column value '016534' converted to 16534 automatically

### ISSUE THREAD

**Issue by babuj03** [alexcaza/export-to-csv#32]
Export excel with string column value '016534' converted to 16534 automatically. I would like to export the same '016534' format when I export to csv

**Comment by vinnydu** [comment]
I need this fix too.

**Comment by alexcaza** [comment]
Unfortunately, there doesn't seem to be a clear-cut solution for this. CSVs don't have much—if any–control over formatting, and it's up to the program opening the CSV to parse the data for display.

One option I've come across is saving it as a `.txt` file instead, and going through the import wizard to determine the formatting yourself. If you look at the raw CSV data, you'll see that the number is properly formatted in plain-text (as of `v1.0.0`).

This article might help: https://www.causal.app/excel/stopping-date-parsing-when-opening-a-csv-file#:~:text=If%20you%20have%20already%20opened,to%20view%20and%20manipulate%20data.
