### ISSUE TITLE
How do I export two table in same excel sheet?

### ISSUE THREAD

**Issue by babuj03** [alexcaza/export-to-csv#33]
I want to export main table and sub table in same excel sheet. Pleae help me  how to do?

**Comment by JefredAllan** [comment]
Any progress on this?

**Comment by tcc-sejohnson** [comment]
Hey @babuj30,

I'm not the maintainer of this library, and I know this is late. But what I'm seeing is that you want to put two "tabs" in the same document. You can't do this with a CSV. You need a "richer" document type for that, such as .xlsx. Check out the JavaScript "XLSX" library.

**Comment by bergamin** [comment]
@babuj03, just to clarify a little better, CSV is not an Excel file. It is a text file built in a pattern that some software like Excel can understand. That pattern might even break on Excel depending on its display language (English Excel uses `,` as a default separator, but Excel might use `;` as default if `,` is used for separating decimals).
