### ISSUE TITLE
Add a returnBlob param in config

### ISSUE THREAD

**Issue by sKuD51** [alexcaza/export-to-csv#35]
Hi, 

I need to just have the blob.
So I updated your code like this : 

`const options = {
    fieldSeparator: ',',
    quoteStrings: '"',
    decimalSeparator: '.',
    showLabels: true,
    showTitle: true,
    title: 'My Awesome CSV',
    useTextFile: false,
    useBom: true,
    useKeysAsHeaders: true,
    returnBlob : true
    // headers: ['Column 1', 'Column 2', etc...] <-- Won't work with useKeysAsHeaders present!
  };`

And in the export-to-csv.js at line 86 I added : 

`if(this._options.returnBlob){
          return blob;
        }else{
          if (navigator.msSaveBlob) {
              var filename = this._options.filename.replace(/ /g, "_") + fileExtension;
              navigator.msSaveBlob(blob, filename);
          }
          else {
              var attachmentType = this._options.useTextFile ? 'text' : 'csv';
              var uri = 'data:attachment/' + attachmentType + ';charset=utf-8,' + encodeURI(this._csv);
              var link = document.createElement("a");
              link.href = URL.createObjectURL(blob);
              link.setAttribute('visibility', 'hidden');
              link.download = this._options.filename.replace(/ /g, "_") + fileExtension;
              document.body.appendChild(link);
              link.click();
              document.body.removeChild(link);
          }
        }`

If you want to implement ;-)

thanks a lot.

**Comment by fromage9747** [comment]
@sKuD51 I did the same thing.  Thank you for the tip.  I hope that this gets added by default

**Comment by alexcaza** [comment]
I'd rather not overload the config API with something like this when you could take the response from `generateCsv` and wrap it in a Blob quite easily doing this:

```typescript
import {generateCsv, asString} from 'export-to-csv';

const output = generateCsv(config)(data);
const blob = new Blob([asString(output)], { type: "text/csv;charset=utf8;" })
```
