### ISSUE TITLE
How do we send the file to download in browser from expressjs

### ISSUE THREAD

**Issue by ekumahost** [alexcaza/export-to-csv#39]
How do we send the file to download in browser from expressJS.

**Comment by alexcaza** [comment]
This isn't directly related to this library. You can look at this StackOverflow question to get an answer. I'd like to keep issues for issues, and not general questions, please :) It can make it overwhelming to go through and triage.

StackOverflow question: https://stackoverflow.com/questions/7288814/download-a-file-from-nodejs-server-using-express
