### ISSUE TITLE
ExportToCsv?

### ISSUE THREAD

**Issue by latimeks** [alexcaza/export-to-csv#4]
I tried running your sample code and got the following error 

**TypeError: ExportToCsv is not a constructor**

**Comment by geoffembuscad0** [comment]
Hi! I tried running your sample sourcecode with expressJS but it doesn't show some reponses even I look at the terminal for error response, heres my code below.

const ExportToCsv = require('export-to-csv');

let data = [
    {
      name: 'Test 1',
      age: 13,
      average: 8.2,
      approved: true,
      description: "using 'Content here, content here' "
    },
    {
      name: 'Test 2',
      age: 11,
      average: 8.2,
      approved: true,
      description: "using 'Content here, content here' "
    },
    {
      name: 'Test 4',
      age: 10,
      average: 8.2,
      approved: true,
      description: "using 'Content here, content here' "
    }
  ];
  const options = {
    fieldSeparator: ',',
    quoteStrings: '"',
    decimalseparator: '.',
    showLabels: true,
    showTitle: true,
    title: 'My Awesome CSV',
    useBom: true,
    useKeysAsHeaders: true
    // headers: ['Column 1', 'Column 2', etc...] <-- Won't work with useKeysAsHeaders present!
  };

  const csvExporter = new ExportToCsv(options);
  csvExporter.generateCsv(data);

**Comment by albertodarblade** [comment]
const ExportToCsv = require('export-to-csv').ExportToCsv;

**Comment by BradPrit09** [comment]
Please close the issue ,it working with ```const ExportToCsv = require('export-to-csv').ExportToCsv;```

**Comment by manumtexperion** [comment]
const {ExportToCsv} = require('export-to-csv');
