### ISSUE TITLE
How to add Multiple Headers. i.e subheaders

### ISSUE THREAD

**Issue by div31** [alexcaza/export-to-csv#40]
I'm trying to export a table which has one common headers and then subheaders. I've attached an image of the result that i want to achieve. From the image you can see that january has three subheaders: cost price, selling price & quantity.  If there is any way to achieve this then please share. 
[](url
![example](https://user-images.githubusercontent.com/56087532/134164826-19eb2124-3db0-40cf-97bf-93a2be574a45.PNG)
)

**Comment by alexcaza** [comment]
CSVs don't support this type of behaviour. To get something like this, you'd have to build an Excel file.
