### ISSUE TITLE
Need a callback function to notify when export is completed

### ISSUE THREAD

**Issue by mjeghers-tmx** [alexcaza/export-to-csv#42]
Please add an option to provide a callback function like "onExportCompleted" so we can know when the work is finished.

**Comment by alexcaza** [comment]
Everything in the library is synchronous. If there's work you'd like to be done after generating the CSV data or issuing the download, you can place that function call immediately afterwards and it should be fine.

If you'd like to react to a download being completed in a browser, there's no API for this library to tap into to make that possible, anyway.

I'm closing this as not planned for now. Please open this issue again with more details and some examples if you'd really like this API to exist.
