### ISSUE TITLE
Field Separator should include the "sep" keyword

### ISSUE THREAD

**Issue by bergamin** [alexcaza/export-to-csv#43]
First line of the generated file should define what the separator character should be. Without that, software like Excel can't understand what to do.

This is good:
```
sep=~
"Column A"~"Column B"~"Column C"
"Line A 1"~"Line A 2"~"Line A 3"
"Line B 1"~"Line B 2"~"Line B 3"
"Line C 1"~"Line C 2"~"Line C 3"
```
![image](https://user-images.githubusercontent.com/14339291/146434057-b518b5ad-2edf-4a3c-abfa-b5bd626ede80.png)

This is bad:
```
"Column A"~"Column B"~"Column C"
"Line A 1"~"Line A 2"~"Line A 3"
"Line B 1"~"Line B 2"~"Line B 3"
"Line C 1"~"Line C 2"~"Line C 3"
```
![image](https://user-images.githubusercontent.com/14339291/146434160-44dcee0e-9ebb-42db-8729-78db063b0c20.png)

**Comment by bergamin** [comment]
@alexcaza, any news on this? Did you get a chance to check it out?

**Comment by alexcaza** [comment]
This was discussed in #36, and a workaround was found.

See [this comment](https://github.com/alexcaza/export-to-csv/issues/36#issuecomment-1742965378) to understanding the reasoning why this was closed.
