### ISSUE TITLE
How to keep array as data?

### ISSUE THREAD

**Issue by juliusoh** [alexcaza/export-to-csv#47]
I have an object that looks like 

`{
  project: 'skynet-dev-335306',
  name: 'pipeline-runner',
  machineType: 'n1-standard-4',
  status: 'TERMINATED',
  zone: 'us-west1-b',
  diskSizeGb: [ '100', '100' ],
  diskType: [ 'PERSISTENT', 'PERSISTENT' ]
}`

But right now 
![image](https://user-images.githubusercontent.com/63981576/191315689-ac2ac0f8-0a0d-457d-97d8-7bee84b10f85.png)

Its taking over next column how do I keep it in same column?

**Comment by alexcaza** [comment]
What I'd recommend is transforming your data to keep it as a string, but join the array data together.

With your example:
```typescript
const data = [
{
    project: 'skynet-dev-335306',
    name: 'pipeline-runner',
    machineType: 'n1-standard-4',
    status: 'TERMINATED',
    zone: 'us-west1-b',
    diskSizeGb: ['100', '100'],
    diskType: ['PERSISTENT', 'PERSISTENT']
},
// <snip> other objects
];

data.map(item => ({
  ...item,
  diskSizeGb: item.diskSizeGb.join(","), 
  diskType: item.diskType.join(",")
}))
```

I don't see this as something the library will ever handle natively. I believe it's up to the caller to transform the data before handing it off to the `generateCsv` function.
