### ISSUE TITLE
If \n present in header column then string not coming in newline in csv file

### ISSUE THREAD

**Issue by pankajvnale** [alexcaza/export-to-csv#51]
There is a multiline column name passed then it is breaking the CSV file columns. If \n is present in the string the column name should break into two lines without changing the CSV file row

**Comment by alexcaza** [comment]
There doesn't seem to be a clear solution to using newlines within data and headers in a CSV yields unwanted behaviours, and it's not something this library will support. It's possible other libraries support this ([see alternatives](https://github.com/alexcaza/export-to-csv#alternatives)). 

If you, or anyone coming along, has an idea for a solution for this. Feel free to open a new issue, or submit a PR with a fix 😄
