### ISSUE TITLE
Support ES6 Modules

### ISSUE THREAD

**Issue by AlexanderMelde** [alexcaza/export-to-csv#55]
Hello Alex,
when importing your script into typescript Angular projects, the following warning appears:

> Warning: [file] depends on 'export-to-csv'. CommonJS or AMD dependencies can cause optimization bailouts.
> For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

I have reviewed the source code here and it seems like this project is not yet a ES Module.
The root project, which is the basis of this fork, seems to have made this change in 2018 [in this commit](https://github.com/javiertelioz/angular2-csv/commit/2c7aa85acbd7b4f943f2bd68e3352dba360d5f4b#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R35). As you can see, they introduce a new module attribute in the package.json file.

For any modern typescript project, it would be helpful if you could provide a ES Module of your fork.

You can read more about the benefits of ESM here: https://dev.to/costamatheus97/es-modules-and-commonjs-an-overview-1i4b

Let me know if I can help during the implementation of this.

Best, 
Alexander

**Comment by alexcaza** [comment]
Which version of the library are you using? v1.0.0 switched to an ES6 module. I spun up a quick Angular test app to import the library using `npm init @angular` and received no warnings.

You can see that the `package.json` file is using `type: "module"`. Can you validate that this is true with version 1.0.0?

https://github.com/alexcaza/export-to-csv/blob/master/package.json#L5

**Comment by AlexanderMelde** [comment]
Hi Alex, sorry! 
My bad, it seems like we are actually using an outdated version of the package. 
Thank you for your help and this great package :)
