### ISSUE TITLE
How do I change name of the file on website?

### ISSUE THREAD

**Issue by Arun-Tiwary** [alexcaza/export-to-csv#76]
**Describe the bug**
A clear and concise description of what the bug is. If possible, include the data you're trying to export as a CSV (with any sensitive data removed; reduced test cases are welcomed).

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Comment by alexcaza** [comment]
I'm not sure I fully understand the question, but I _think_ you want the `filename` option that's listed in the API section of the readme.

Link: https://github.com/alexcaza/export-to-csv?tab=readme-ov-file#api

If that doesn't answer you're question, please open a new issue and add more details and follow the template 😄
