### ISSUE TITLE
Error when using in ESM project

### ISSUE THREAD

**Issue by egmacke** [alexcaza/export-to-csv#78]
**Describe the bug**

When using this library in a project set to use ESM project fails to build with import error:
```
export-to-csv/output/index.d.ts:1:15 - error TS2834: Relative import paths need explicit file extensions in EcmaScript imports when '--moduleResolution' is 'node16' or 'nodenext'. Consider adding an extension to the import path.
```

**To Reproduce**

1. Create a new project, or open existing
2. Ensure project is set to use ESM (moduleResolution: node16)
3. Build project

When I get a few minutes I'll put an example repo together if needed.

**Expected behavior**
Project should build.

**Desktop (please complete the following information):**

- OS: Unix
- Browser nodejs
- Version 20

**Comment by alexcaza** [comment]
If you don't mind creating a repo I could clone, that would be great. If not, then sharing your `tsconfig.json` and `package.json` at a minimum would be great.

I can't reproduce the error with `type: "module"` set in `package.json` and `module: "node16"` and `moduleResolution: "node16"` set in `tsconfig.json`.

**Comment by jirutka** [comment]
I encountered the same problem.

```jsonc
{
  "compilerOptions": {
    /* Visit https://aka.ms/tsconfig to read more about this file */

    /* Language and Environment */
    "target": "ES2020",                                  /* Set the JavaScript language version for emitted JavaScript and include compatible library declarations. */
    "jsx": "react",                                      /* Specify what JSX code is generated. */

    /* Modules */
    "module": "Node16",                                  /* Specify what module code is generated. */
    "moduleResolution": "Node16",                        /* Specify how TypeScript looks up a file from a given module specifier. */
    "baseUrl": "./src",                                  /* Specify the base directory to resolve non-relative module names. */
    "resolveJsonModule": true,                           /* Enable importing .json files. */

    /* Interop Constraints */
    "esModuleInterop": true,                             /* Emit additional JavaScript to ease support for importing CommonJS modules. This enables 'allowSyntheticDefaultImports' for type compatibility. */
    "preserveSymlinks": true,                            /* Disable resolving symlinks to their realpath. This correlates to the same flag in node. */
    "forceConsistentCasingInFileNames": true,            /* Ensure that casing is correct in imports. */

    /* Type Checking */
    "strict": true,                                      /* Enable all strict type-checking options. */
    "noUnusedLocals": true,                              /* Enable error reporting when local variables aren't read. */
    "noUnusedParameters": true,                          /* Raise an error when a function parameter isn't read. */
    "noImplicitReturns": true,                           /* Enable error reporting for codepaths that do not explicitly return in a function. */
    "noFallthroughCasesInSwitch": true,                  /* Enable error reporting for fallthrough cases in switch statements. */
    "noImplicitOverride": true,                          /* Ensure overriding members in derived classes are marked with an override modifier. */

    /* Completeness */
    "skipLibCheck": false,                                /* Skip type checking all .d.ts files. */
  },
  "include": [
    "src/**/*",
  ],
}
```

**Comment by alexcaza** [comment]
Thanks for sharing! I'm able to reproduce this issue now and I'll look into it.

**Comment by alexcaza** [comment]
I just opened a PR for this (https://github.com/alexcaza/export-to-csv/pull/79).

Could @jirutka or @egmacke try cloning the project and pointing their project to the cloned code before I publish a new version?

The test project I created works correctly, but I'd like to avoid any back-and-forth if I've missed something 😄

**Comment by egmacke** [comment]
@alexcaza thanks for getting this sorted so quickly.

I've forked and tested and aside from a few issues that I've recorded on the PR, it all works as expected.

My only other question is whether this is backwards compatible? I don't have a project setup where I can check, but maybe worth marking this as a possible breaking change?

**Comment by alexcaza** [comment]
The package was updated to v1.2.3, which fixes this issue. Feel free to open a new issue and reference this one if something is still off of new issues pop up :)

https://www.npmjs.com/package/export-to-csv/v/1.2.3

**Comment by jirutka** [comment]
The latest version works, thanks!

**Comment by egmacke** [comment]
Working nicely for me thanks!
