### ISSUE TITLE
Filename doesn't seem to work in options

### ISSUE THREAD

**Issue by snadella3** [alexcaza/export-to-csv#8]
Hi, I have the options this way:
const options = {
            fieldSeparator: ',',
            filename: 'response_time',
            quoteStrings: '"',
            decimalSeparator: '.',
            showLabels: true,
            showTitle: false,
            title: 'report',
            useTextFile: false,
            useBom: true,
            useKeysAsHeaders: true,
        };
        const csvExporter = new ExportToCsv(options);
        csvExporter.generateCsv(data);

and th file is still downloaded with some random generated file name. Any idea what i might be doing wrong here

**Comment by mwolfhoffman** [comment]
Also experiencing this issue.

**Comment by jnfaerch** [comment]
Could this issue be closed? I use this and it works perfectly regarding the `filename`

```
    exportCsvFile(objects: Object[], name: string) {
        const options = {
            fieldSeparator: ',',
            filename: `${ name }_${ Date() }`,
            quoteStrings: '"',
            decimalSeparator: '.',
            showLabels: true,
            showTitle: false,
            title: name,
            useTextFile: false,
            useBom: true,
            useKeysAsHeaders: true
          };
        const csvExporter = new ExportToCsv(options);
        return csvExporter.generateCsv(objects);
    }
```

**Comment by lomse** [comment]
Currently, empty spaces are replaced with `_`. Is it possible to generate csv file without replacing empty spaces ty `_`?

**Comment by kishore-s-15** [comment]
Even after having the `filename` property with no spaces, this issue still persists for me. It just doesn't seem to work.

**Code that I've used:**

```typescript
const downloadResults = () => {
        const options = {
            fieldSeparator: ",",
            quoteStrings: '"',
            decimalSeparator: ".",
            showLabels: true,
            fileName: "tagged_sentences.csv",
            useTextFile: false,
            useBom: true,
            useKeysAsHeaders: true,
        };

        const csvExporter = new ExportToCsv(options);
        csvExporter.generateCsv(downloadableResults);
};
```

**Comment by lalitdhami007** [comment]
i also tried it. file is still downloaded with some random generated file name

**Comment by KiligFei** [comment]
Me too, the file name is not effective

**Comment by alexcaza** [comment]
As of `v1.x.x` file name support works as expected, and you can now use a file name with spaces.
