### ISSUE TITLE
Failed to parse source map

### ISSUE THREAD

**Issue by SumitUnhale** [alexcaza/export-to-csv#92]
In my React application, I am getting issue like  Error: ENOENT: no such file or directory, open \node_modules\export-to-csv\build\export-to-csv.js.map', Please help me for resolving this issue.

![issue](https://github.com/alexcaza/export-to-csv/assets/161868847/7ba13894-f0fa-40a1-9bef-f4190247b427)

**Comment by alexcaza** [comment]
This seems to be a known issue with `create-react-app` and its internal Webpack configuration. This library doesn't ship sourcemaps—and doesn't reference them within `index.js`, either. There's not much I can do as I don't think shipping the sourcemaps would be helpful anyway.

Link to the pull request talking about this issue on the `create-react-app` repo: https://github.com/facebook/create-react-app/pull/11752
